El 41 umschalten zwischen darstellungsformen
eventlogs/event_logs pull request #14
Opened 2022-06-14 08:12 UTC by eawetchy

Beinhaltet schon EL-10-Branch und EL-42, Review also am besten erst, nachdem diese gemergt sind.
Umschalt-Button befindet sich oben links 😆

2022-06-14 20:14 UTC, TobStr90 requested changes
Es wurden teilweise deutsche Bezeichner verwendet. Die weitere Vorgehensweise diesbezüglich wird im nächsten Sprint Review besprochen.

Linting sollte noch durchgeführt werden.

Beim Umschalten verschiebt sich der Bereich unterhalb der Zeichenfläche geringfügig. Dies könnte wegen dem fehlenden Scrolling vom Direkt-Folge-Graphen entstehen.

Wird auf den Direkt-Folge-Graphen umgeschaltet und eine neue .log Datei importiert, wird das 3 Event in der Wertschöpfungskette teilweise abgeschnitten.
![Wertschöpfungskette abgeschnitten](https://user-images.githubusercontent.com/65013412/173679974-91e92cb7-f034-4418-b42d-8573f7eb355a.PNG)

2022-06-15 12:56 UTC, eawetchy commented
> Linting sollte noch durchgeführt werden.
Ist erledigt

> Beim Umschalten verschiebt sich der Bereich unterhalb der Zeichenfläche geringfügig. Dies könnte wegen dem fehlenden Scrolling vom Direkt-Folge-Graphen entstehen.
Wurde behoben

> Wird auf den Direkt-Folge-Graphen umgeschaltet und eine neue .log Datei importiert, wird das 3 Event in der Wertschöpfungskette teilweise abgeschnitten.
Dieses Problem ist behoben, ein ähnliches Problem wie in https://eventlogs.atlassian.net/browse/EL-44 besteht noch und ich habe es bisher ums Verrecken nicht beheben können, drum schlage ich vor, diesen Bug in den nächsten Sprint mit aufzunehmen.

2022-06-15 12:56 UTC, eawetchy commented
> Linting sollte noch durchgeführt werden.
Ist erledigt

> Beim Umschalten verschiebt sich der Bereich unterhalb der Zeichenfläche geringfügig. Dies könnte wegen dem fehlenden Scrolling vom Direkt-Folge-Graphen entstehen.
Wurde behoben

> Wird auf den Direkt-Folge-Graphen umgeschaltet und eine neue .log Datei importiert, wird das 3 Event in der Wertschöpfungskette teilweise abgeschnitten.
Dieses Problem ist behoben, ein ähnliches Problem wie in https://eventlogs.atlassian.net/browse/EL-44 besteht noch und ich habe es bisher ums Verrecken nicht beheben können, drum schlage ich vor, diesen Bug in den nächsten Sprint mit aufzunehmen.

2022-06-15 13:30 UTC, TobStr90 approved these changes
Sieht gut aus, super!

2022-06-15 13:32 UTC, merged