Kanten mit gleichem Start- und Endknoten geändert
eventlogs/event_logs pull request #34
Opened 2022-07-11 09:55 UTC by TobStr90

2022-07-15 14:53 UTC, yannikworthmann requested changes
Generell scheint die Darstellung nun zu stimmen, denn folgendes Beispiel wird mir korrekt angezeigt:
.type log
.attributes
case-id
activity
.events
1 Auto
1 Schiff
1 Auto
2 Bus
2 Auto
2 Bus
2 Bus


Wenn ich jedoch das folgende Beispiel ansehen möchte, dann sehe ich gar keinen Direkt-Folge-Graph:
.type log
.attributes
case-id
activity
.events
1 Auto
1 Auto
2 Bus
2 Bus

2022-07-15 14:53 UTC, yannikworthmann commented on src/app/services/directly-follows-graph/svg.service.ts
> +        console.log(coordinates);
Dieses console.log kann sicherlich noch entfernt werden.

2022-07-16 18:10 UTC, TobStr90 commented on src/app/services/directly-follows-graph/svg.service.ts
> +        console.log(coordinates);
Das unnötige console.log wurde entfernt.
Der von dir beschriebene Bug wird/wurde mit https://github.com/eventlogs/event_logs/pull/36 behoben.

2022-07-17 11:15 UTC, yannikworthmann approved these changes

2022-07-17 11:15 UTC, merged