Canvas in DIV-gewrappt für Scrollen, Layoutservice
eventlogs/event_logs pull request #9
Opened 2022-06-02 19:39 UTC by ThomasKaputa

berechnet Ausdehnung der Zeichnung, wrappen von Canvas in Div mit Scrollbalken. Unittests für LayoutService hinzugefügt..
die Typescript Version habe ich nur anpassen müssen da ich sonst nach einem frischen npm install nicht mehr compilen konnte

2022-06-06 16:07 UTC, eawetchy commented
Puh, ich hatte auch grad viel Spaß, die Sache wieder zum Laufen zu bringen! Hast du irgendeine Ahnung, was das ausgelöst haben könnte? 🤔
Ich glaube, letztendlich hat es bei mir folgendes getan:
- Ordner löschen und neu klonen
- `npm cache verify`
- `npm install`
Danach ging's auch mit dem alten Eintrag für die Typescript-Version wieder (^4.5.5) - kannst du das mal bei dir ausprobieren? Ich würds gerne klären, damit ich nicht später irgendwann wieder eine Stunde mit Angular troubleshooten verbringen muss 😅

2022-06-06 16:09 UTC, eawetchy commented
Das `import { IfStmt } from '@angular/compiler';` in **display.component.ts** scheint nicht benutzt zu sein, den Import könnten wir also entfernen

2022-06-06 16:28 UTC, eawetchy commented
Tests für den Layout-Service find ich super, vielleicht kannst du die verschiedenen Zahlenwerte wie z.B. "Offset zur Mitte vom Trace" als Variablen einmal definieren, dann könntest du das erwartete Ergebnis daraus zusammensetzen? Die Kommentare, die genau das erklären, bräuchte es dann nicht, und du musst es nur an einer Stelle ändern, falls wir später noch mal das Layout ändern :)

2022-06-08 15:40 UTC, ThomasKaputa commented
> 

Hab es endlich hingekriegt... Musste tatsächlich node komplett neu installieren dann gehts  auch wieder ohne änderung im package.json

2022-06-08 15:52 UTC, ThomasKaputa commented
Hab alles angepasst was du gesagt hast. Super Idee mit den Variablenamen im Test!

2022-06-09 10:17 UTC, eawetchy requested changes
Die neuen Variablennamen für Breite und Höhe müssten in `display.component.html` noch angepasst werden, sonst kriegen wir einen Fehler beim Kompilieren. Dann sollten wir soweit bereit zum Mergen sein!

Mir ist beim Testen von der "zu_viele_traces2.txt"-Datei auch noch aufgefallen, dass da scheinbar ganz rechts drüben eine partielle Box zu sehen ist - weiꞵ nicht, ob das ein Fehler beim Zeichnen ist oder ob der Trace da abgeschnitten ist?
Das muss nicht unbedingt in diesem PR korrigiert werden, aber in dem Fall sollten wirs noch als Bug im Backlog festhalten!
![image](https://user-images.githubusercontent.com/10432999/172824269-1b6d6529-a18f-4c73-918a-e7c5ef947c59.png)

2022-06-09 10:53 UTC, ThomasKaputa commented
@eawetchy 
So jetzt aber sorry! File ist comittet.
Das ist mir tatsächlich noch nicht aufgefallen. Wenn man einen Trace ändert und der Zeichenbereich refresht scheint sich das Problem selbst zu lösen..
Vielleicht hängt das wirklich mit dem sehr großen Trace und irgendwelchen Mindestwerten für die Scrollbar zusammen. Dafür sollten wir einen extra Bug aufnehmen. Ich kann ihn aufnehmen heute Abend falls du es nicht schon gemacht hast.

2022-06-09 10:58 UTC, eawetchy approved these changes

2022-06-09 11:05 UTC, merged

2022-06-09 11:06 UTC, eawetchy commented
Und gemergt :)
Ah ja, das stimmt. nach dem zweiten Ruckeln ist alles so gezeichnet, wie es sein soll. Ich hab einen Bug erstellt: https://eventlogs.atlassian.net/browse/EL-44